### ISSUE TITLE
Replace ‘BEM grid‘ example with Bootstrap

### ISSUE THREAD

**Issue by ihorzenich** [AleshaOleg/holy-grail-markup#12]
Bootstrap v4 uses flexbox too, but `bootstrap-example‘ will be more popular.
Also we should mix some common Bootstrap elements with design to show **how BEM can be implemented with Bootstrap**

**Comment by AleshaOleg** [comment]
I think we should wait until Bootstrap 4 will be officially realized, and then make this example with flexboxes.

**Comment by AleshaOleg** [comment]
Implemented in `bem-bootstrap-4` directory.
