### ISSUE TITLE
Add stats

### ISSUE THREAD

**Issue by Jabher** [AleshaOleg/holy-grail-markup#2]
I think, some stats for each impl in README.md would be useful, like:
- number of lines in HTML/CSS
- number of CSS declarations
- filesize
etc

**Comment by ihorzenich** [comment]
@Jabher Thanks, that makes sense.

**Comment by AleshaOleg** [comment]
@Jabher Thanks for idea! I implemented stats [here](https://github.com/AleshaOleg/holy-grail-markup#statistics), please take a look on it and say what you think about it. Thanks.

**Comment by Jabher** [comment]
wow, that's a lot of data :) It's a great work you did.

Only objective criticism is that no explanation is given for S/R and D/R.

Also I'd rather keep all of this data in one table instead of multiple, like this:

Implementation|HTML lines|CSS lines|...
-|-|-|-
Atomic|104|220|...
BEM CSS|104|179|...
...|...|...|...

so it would be more comparable

**Comment by AleshaOleg** [comment]
@Jabher yes, it make sense, will merge all table in one in the evening. Thanks, again!

**Comment by Jabher** [comment]
@AleshaOleg Thank you, guys, you're making a great work and I'm just standing here with advices :)

**Comment by AleshaOleg** [comment]
@Jabher fixed, and deployed to master.
