### ISSUE TITLE
„BEM platform“ variant design not match the others

### ISSUE THREAD

**Issue by ihorzenich** [AleshaOleg/holy-grail-markup#23]
After “Add implementation on BEM Platform #18” we get some minor issues with design - for now „bem platform“ variant view not match the others.

We think - minor problems can help better understand technology, so fixes to design may be a perfect example of customizing bem-blocks under BEM Platform. We need help with it.

@tadatuta would you help us?

**Comment by tadatuta** [comment]
ok, will send a pr in a while

**Comment by AleshaOleg** [comment]
@tadatuta hey, how it's going? We really wait for your PR and will appreciate it! Soon we also will have an examples of css-in-js, and ITCSS. So, your PR good complement this collection:) Thanks!

**Comment by tadatuta** [comment]
@AleshaOleg see https://github.com/AleshaOleg/holy-grail-markup/pull/25

**Comment by ihorzenich** [comment]
@tadatuta Thank you for providing us with such a great working example!
