### ISSUE TITLE
Were atomic styles generated by a preprocessor? Are there any less/sass/etc sources?

### ISSUE THREAD

**Issue by ArturBaybulatov** [AleshaOleg/holy-grail-markup#29]

**Comment by AleshaOleg** [comment]
@ArturBaybulatov Hey! There is no styles like LESS/Sass. All styles generates from class names. [Here](https://github.com/AleshaOleg/holy-grail-markup/blob/master/atomic/index.html#L7) is example. Take a look for Atomic [docs](https://acss.io/guides/atomic-classes.html) for style class names.

Then Gulp plugin for atomic [helps](https://github.com/AleshaOleg/holy-grail-markup/blob/master/atomic/Gulpfile.js#L18) to converts class names to styles. [Here](https://github.com/AleshaOleg/holy-grail-markup/blob/master/atomic/style.css) is CSS output.

Thanks for your question. Is everything clear for you now? Can I close this issue?

**Comment by ArturBaybulatov** [comment]
Oh, now i see. Sorry for a silly question. Thanks for an amazing website!
