### ISSUE TITLE
Maybe wrong credit for alternative BEM naming in README

### ISSUE THREAD

**Issue by idmytro** [AleshaOleg/holy-grail-markup#32]
Do not trust wikipedia :)
https://gist.github.com/necolas/1309546/revisions

**Comment by AleshaOleg** [comment]
What you mean?

**Comment by idmytro** [comment]
This style of naming was developed by Nicolas Gallagher, not Harry Robberts. 

See https://csswizardry.com/2013/01/mindbemding-getting-your-head-round-bem-syntax/

> It is important to note that I use a naming scheme based on BEM, but honed by Nicolas Gallagher.

**Comment by AleshaOleg** [comment]
I will mention @ihorzenich. This one his topic:)

**Comment by AleshaOleg** [comment]
@idmytro you're right, I updated README and mention Nicolas Gallagher as a creator of alternative BEM naming, also saved Harry Roberts mention because he make this methodology popular.
