### ISSUE TITLE
Remove ACSS class from SMACSS index file

### ISSUE THREAD

**Issue by thierryk** [AleshaOleg/holy-grail-markup#39]
I see this on [line 15](https://github.com/AleshaOleg/holy-grail-markup/blob/c938c8a8de68c55c5587c5a7336731bc5086a172/smacss/index.html#L15)

```html
<form class="header-search Bd(1px,solid,#000)">
```
As far as I know, `Bd(1px,solid,#000)` is Atomic CSS, not SMACSS.

**Comment by AleshaOleg** [comment]
@thierryk Sure, you're right.

**Comment by AleshaOleg** [comment]
I will fix this one, today.

**Comment by AleshaOleg** [comment]
Done. https://github.com/AleshaOleg/holy-grail-markup/blob/master/smacss/index.html#L15
Can be closed.
