### ISSUE TITLE
Remove type attribute from <link>

### ISSUE THREAD

**Issue by thierryk** [AleshaOleg/holy-grail-markup#40]
I noticed a discrepancy between index files regarding the use of `type="text/css"`. For example, the SMACSS [index file](https://github.com/AleshaOleg/holy-grail-markup/blob/c938c8a8de68c55c5587c5a7336731bc5086a172/smacss/index.html#L5) contains `<link rel="stylesheet" href="basic.css">` but the "Atomic" [index file](https://github.com/AleshaOleg/holy-grail-markup/blob/b6d3b130e4bbe5a2f4d5eca901fa9f922929c550/atomic/index.html#L5) contains `<link rel="stylesheet" href="style.css" type="text/css">`.

I think `type="text/css"` should be removed across the board altogether.

**Comment by idmytro** [comment]
done
