### ISSUE TITLE
Add link to "BEM SASS" for 'bem-platform' metodology

### ISSUE THREAD

**Issue by SenDen111** [AleshaOleg/holy-grail-markup#48]
When I implemented 'bem-sass' methodology, I added links to it for all other methodologies at sidebar, except 'bem-platform'. 
Looks like to implement changes it has to be built. And I'm not sure I would make it correctly. 
I guess there should be added an object similar to the one for css:
``` 
{
    url: 'https://aleshaoleg.github.io/holy-grail-markup/bem-css/',
    content: 'BEM CSS'
},
```
And command 'node build' run.

**Comment by SenDen111** [comment]
@tadatuta could you confirm my guesses please, or let me know if I'm mistaken.

**Comment by tadatuta** [comment]
@SenDen1 yes, looks reasonable

**Comment by SenDen111** [comment]
@AleshaOleg @ihorzenich 
Created PR for fixing this issue: https://github.com/AleshaOleg/holy-grail-markup/pull/50

**Comment by ihorzenich** [comment]
@SenDen1 merged, thanks!
