### ISSUE TITLE
Replace ’grunt-contrib-sass’ with ’grunt-sass’ for ’Organic CSS’

### ISSUE THREAD

**Issue by ihorzenich** [AleshaOleg/holy-grail-markup#6]
So we don't have to use Ruby Sass there.

**Comment by AleshaOleg** [comment]
Fixed, now issue should be closed.

https://github.com/AleshaOleg/holy-grail-markup/commit/1ac213cb0ec4ac6b985c9b7875ce08b7146e5f3d
