### ISSUE TITLE
Rewrite ’BEM’ example with Sass

### ISSUE THREAD

**Issue by ihorzenich** [AleshaOleg/holy-grail-markup#8]
Because usually BEM is written with Sass, and using `&__` shows block decomposition better.

**Comment by AleshaOleg** [comment]
Fixed. Now issue, should be closed.

https://github.com/AleshaOleg/holy-grail-markup/commit/1ac213cb0ec4ac6b985c9b7875ce08b7146e5f3d

**Comment by SenDen111** [comment]
@AleshaOleg @ihorzenich 
Will handle this one

**Comment by AleshaOleg** [comment]
@SenDen1 great, thanks!

**Comment by ihorzenich** [comment]
Done in https://github.com/AleshaOleg/holy-grail-markup/pull/47#pullrequestreview-143967589
